### ISSUE TITLE
ansible_distribution should be used as lowercase in URLs

### ISSUE THREAD

**Issue by toozej** [toozej/ansible#26]
https://travis-ci.org/toozej/ansible/jobs/240949917

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_fjSmIu/ansible_module_apt_repository.py", line 565, in <module>
    main()
  File "/tmp/ansible_fjSmIu/ansible_module_apt_repository.py", line 553, in main
    cache.update()
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 440, in update
    raise FetchFailedException(e)
apt.cache.FetchFailedException: W:Failed to fetch http://linux.dropbox.com/Ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found [IP: 52.84.64.73 80]
, W:Failed to fetch http://linux.dropbox.com/Ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found [IP: 52.84.64.73 80]
, E:Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by toozej** [comment]
fixed
